title: Reyson Angeles
logo: /assets/img/Profile.png
description: Developer Ops / Automation Engineer
#show_downloads: true
# Add social links
social_links:
  linkedin: https://www.linkedin.com/in/reysonangeles/
  facebook: https://www.facebook.com/reyson.angeles/
theme: jekyll-theme-minimal
